version: "3"

services:
    autoheal:
        container_name: autoheal
        restart: always
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
            - APPRISE_URL=http://10.99.100.42:8010/notify/0481f9f37364020768d08179fb48e6c96da1b022e2db4a5357fc21b29a89631c
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        image: willfarrell/autoheal

    apprise-api:
        # mailtos://sharedsvcs.com?user=nocreport&pass=IqPsAdhtwDve77Sp&smtp=mail.smtp2go.com&from=nocreport@sharedsvcs.com&to=NOCTools@buckeyebroadband.com
        image: lscr.io/linuxserver/apprise-api:latest
        container_name: apprise-api
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Detroit
        volumes:
            - apprise-api:/config
        ports:
            - 8010:8000
        restart: unless-stopped

volumes:
  apprise-api: