version: "3"

services:
  grafana-nois-telesystem-demo-instance:
    image: grafana/grafana-oss:10.3.1
    container_name: grafana-nois-telesystem-demo-instance
    environment:
      - GF_SERVER_DOMAIN="trusttelesystem.nois.cloud"
      - GF_SERVER_ROOT_URL=https://trusttelesystem.nois.cloud/
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_PUBLIC_MODE=false
      - GF_AUTH_LDAP_ENABLED=true
      - GF_ALLOW_SIGN_UP=true
      - GF_SECURITY_PUBLIC_MODE=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=gapit-htmlgraphics-panel,yesoreyeram-infinity-datasource
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/opt/common-provisioning-assets/dashboards/landing-production.json
      - GF_EXPLORE_ENABLED=false
      - GF_HELP_ENABLED=false
      - GF_PROFILE_ENABLED=true
      - GF_NEWS_NEWS_FEED_ENABLED=false
      - GF_SNAPSHOTS_ENABLED=false
      - GF_METRICS_ENABLED=false
      - GF_PLUGINS_DISABLE_PLUGINS="alertlist,annolist,dashlist,news,table-old,traces,flamegraph,graphite,opentsdb,mssql,tempo,jaeger,zipkin,azuremonitor,cloudwatch,cloud-monitoring,parca,phlare,grafana-pyroscope-datasource"
    volumes:
      # Grafana data
      - grafana-nois-telesystem-demo-instance-data:/var/lib/grafana
      # Add the custom landing page background
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/img/landing_bg.webp:/usr/share/grafana/public/img/landing_bg.webp
      # Customized images
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/img/fav32.png:/usr/share/grafana/public/img/fav32.png
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/img/fav32.png:/usr/share/grafana/public/img/apple-touch-icon.png
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/img/logo.svg:/usr/share/grafana/public/img/grafana_icon.svg
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/img/background.svg:/usr/share/grafana/public/img/g8_login_dark.svg
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/img/background.svg:/usr/share/grafana/public/img/g8_login_light.svg
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/img/nois_logo_text_light.png:/usr/share/grafana/public/img/nois_logo_text_dark.png
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/img/nois_logo_text_dark.png:/usr/share/grafana/public/img/nois_logo_text_light.png
      # Add the provisioning files
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/provisioning/customer_preferences.json:/usr/share/grafana/public/customer_preferences.json
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      - /opt/docker_apps/customer_data/common-provisioning-assets:/opt/common-provisioning-assets/
      # Add LDAP configuration
      - /opt/docker_apps/customer_data/telesystem-demo/grafana/ldap.toml:/etc/grafana/ldap.toml:ro
    networks:
      - nois-customer-instances
    ports:
      - 3006:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  grafana-nois-telesystem-demo-instance-data:

networks:
  nois-customer-instances: