version: "3"

services:
  nois-honeybakedham-instance:
    image: ghcr.io/shared-services-bci/grafana:nois-dev
    container_name: nois-honeybakedham-instance
    environment:
      - GF_SERVER_DOMAIN="hbh.nois.cloud"
      - GF_SERVER_ROOT_URL=https://hbh.nois.cloud
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_PUBLIC_MODE=false
      - GF_AUTH_LDAP_ENABLED=true
      - GF_ALLOW_SIGN_UP=true
      - GF_SECURITY_PUBLIC_MODE=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/opt/common-provisioning-assets/dashboards/meta_call_data.json
      - GF_EXPLORE_ENABLED=false
      - GF_HELP_ENABLED=false
      - GF_PROFILE_ENABLED=true
      - GF_NEWS_NEWS_FEED_ENABLED=false
      - GF_SNAPSHOTS_ENABLED=false
      - GF_METRICS_ENABLED=false
      - GF_PLUGINS_DISABLE_PLUGINS="alertlist,annolist,dashlist,news,table-old,traces,flamegraph,graphite,opentsdb,mssql,tempo,jaeger,zipkin,azuremonitor,cloudwatch,cloud-monitoring,parca,phlare,grafana-pyroscope-datasource"
    volumes:
      # Grafana data
      - nois-honeybakedham-instance-data:/var/lib/grafana
      # Add the provisioning files
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      - /mnt/app_shared_storage/customer_data/common-provisioning-assets:/opt/common-provisioning-assets/
      # Add LDAP configuration
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/ldap.toml:/etc/grafana/ldap.toml:ro
    ports:
      - 3010:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 60s
      retries: 5

volumes:
  nois-honeybakedham-instance-data: