version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /mnt/ceph/docker-apps/nginx/conf.d:/etc/nginx/conf.d:ro
      - /mnt/ceph/docker-apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/ceph/docker-apps/nginx/ssl/reports.ua.sharedsvcs.com.cer:/etc/nginx/ssl/reports.ua.sharedsvcs.com.cer:ro
      - /mnt/ceph/docker-apps/nginx/ssl/reports.ua.sharedsvcs.com.key:/etc/nginx/ssl/reports.ua.sharedsvcs.com.key:ro
      - /mnt/ceph/docker-apps/nginx/ssl/wildcard.nois.cloud.cer:/etc/nginx/ssl/wildcard.nois.cloud.cer:ro
      - /mnt/ceph/docker-apps/nginx/ssl/wildcard.nois.cloud.key:/etc/nginx/ssl/wildcard.nois.cloud.key:ro
      - /mnt/ceph/docker-apps/nginx/logs:/etc/nginx/logs
    ports:
      - "80:80"
      - "443:443"
    restart: always
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == manager]