version: "3"

services:
  nois-honeybakedham-instance:
    image: ghcr.io/shared-services-bci/grafana:nois-telesystem
    container_name: nois-honeybakedham-instance
    environment:
      - GF_SERVER_DOMAIN="hbh.nois.cloud"
      - GF_SERVER_ROOT_URL=https://hbh.nois.cloud
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_PUBLIC_MODE=false
      - GF_AUTH_LDAP_ENABLED=true
      - GF_ALLOW_SIGN_UP=true
      - GF_SECURITY_PUBLIC_MODE=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/opt/common-provisioning-assets/dashboards/landings/landing-production.json
      - GF_EXPLORE_ENABLED=false
      - GF_HELP_ENABLED=false
      - GF_PROFILE_ENABLED=true
      - GF_NEWS_NEWS_FEED_ENABLED=false
      - GF_SNAPSHOTS_ENABLED=false
      - GF_METRICS_ENABLED=false
      - GF_PLUGINS_DISABLE_PLUGINS="alertlist,annolist,dashlist,news,table-old,traces,flamegraph,graphite,opentsdb,mssql,tempo,jaeger,zipkin,azuremonitor,cloudwatch,cloud-monitoring,parca,phlare,grafana-pyroscope-datasource"
      - GF_INSTALL_PLUGINS=gapit-htmlgraphics-panel
    volumes:
      # Grafana data
      - nois-honeybakedham-instance-data:/var/lib/grafana
      # Customized images
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/img/landing_bg.webp:/usr/share/grafana/public/img/landing_bg.webp
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/img/HBH_Logo.png:/usr/share/grafana/public/img/whiteLabel_logo_top_left.png
      # Add the provisioning files
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/provisioning/customer_preferences.json:/usr/share/grafana/public/customer_preferences.json
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      - /mnt/app_shared_storage/customer_data/common-provisioning-assets:/opt/common-provisioning-assets/
      # Add LDAP configuration
      - /mnt/app_shared_storage/customer_data/nois-honeybakedham/grafana/ldap.toml:/etc/grafana/ldap.toml:ro
    ports:
      - 3000:3000
    networks:
      - honeybakedham-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 60s
      retries: 5

  honeybakedham-meta-ingester:
    image: ghcr.io/shared-services-bci/meta_csv_ingester:dev
    container_name: Meta_CSV_Ingester
    environment:
      - DATABASE_HOST=honeybakedham-timescaledb
      - DATABASE_PORT=5432
      - DATABASE_NAME=meta_call_data
      - DATABASE_USERNAME=meta_user
      - DATABASE_PASSWORD=K3ZppUK2h4qdLkRF
      - RUNTIME_MINUTE_INTERVAL=2
      - PBX_USERNAME=7007000010
      - PBX_PASSWORD=9KtKi4wiDWmEA!U
    restart: unless-stopped
    networks:
      - honeybakedham-network
      
  honeybakedham-timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: Meta_CSV_Ingester_Postgres
    environment:
      - POSTGRES_DB=meta_call_data
      - POSTGRES_USER=meta_user
      - POSTGRES_PASSWORD=K3ZppUK2h4qdLkRF
    volumes:
      - nois-honeybakedham-timescaledb-data:/home/postgres/pgdata/data
    restart: unless-stopped
    networks:
      - honeybakedham-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "meta_call_data"]
      interval: 30s
      timeout: 60s
      retries: 5

volumes:
  nois-honeybakedham-instance-data:
  nois-honeybakedham-timescaledb-data:

networks:
  honeybakedham-network: